# Generated by Django 4.2.23 on 2025-10-17 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=45)),
                ('cena', models.IntegerField()),
                ('velicina_serviranja', models.CharField(max_length=45)),
                ('kolicina_na_stanju', models.IntegerField()),
            ],
            options={
                'db_table': 'artikal',
            },
        ),
        migrations.CreateModel(
            name='Polje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'polje',
            },
        ),
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'racun',
            },
        ),
        migrations.CreateModel(
            name='TipArtikla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tip_artikla',
            },
        ),
        migrations.CreateModel(
            name='Zaposleni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zap', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zaposleni',
            },
        ),
        migrations.CreateModel(
            name='Sto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.polje')),
            ],
            options={
                'db_table': 'sto',
            },
        ),
        migrations.CreateModel(
            name='Stavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.artikal')),
                ('racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.racun')),
            ],
            options={
                'db_table': 'stavka',
            },
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vreme', models.DateTimeField()),
                ('ime', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=15)),
                ('sto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.sto')),
            ],
            options={
                'db_table': 'rezervacija',
            },
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.FloatField()),
                ('konobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.zaposleni')),
                ('racun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.racun')),
            ],
            options={
                'db_table': 'recenzija',
            },
        ),
        migrations.AddField(
            model_name='racun',
            name='konobar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.zaposleni'),
        ),
        migrations.AddField(
            model_name='racun',
            name='sto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.sto'),
        ),
        migrations.CreateModel(
            name='Dostava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField()),
                ('jedinicna_cena', models.IntegerField()),
                ('status', models.CharField(max_length=15)),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.artikal')),
            ],
            options={
                'db_table': 'dostava',
            },
        ),
        migrations.AddField(
            model_name='artikal',
            name='tip_artikla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.tipartikla'),
        ),
    ]
