# Generated by Django 4.2.23 on 2025-10-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('broj_smene', models.IntegerField()),
                ('konobar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekat.zaposleni')),
            ],
            options={
                'db_table': 'smena',
            },
        ),
    ]
