# Generated by Django 4.2.23 on 2025-10-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projekat', '0002_smena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dostava',
            name='jedinicna_cena',
        ),
    ]
