# Generated by Django 5.2.7 on 2025-10-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekat', '0003_remove_dostava_jedinicna_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzija',
            name='ocena',
            field=models.IntegerField(),
        ),
    ]
