# Generated by Django 4.2.23 on 2025-10-24 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projekat', '0004_alter_recenzija_ocena'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='datum_otvaranja',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
